# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

user = User.create(
    :first_name => 'John', :last_name => 'Testuser', :email => 'testuser@testuser.com', blurb: 'blurb blurb blurb blurb blurb', remote_profile_pic_url: "http://bloximages.chicago2.vip.townnews.com/journalstar.com/content/tncms/assets/v3/editorial/e/85/e8588925-93ad-5923-ad37-7b1fbc25d5e4/5022d8cf9445e.preview-620.jpg",:password => 'topsecret', :password_confirmation => 'topsecret', :admin => 'true'
)

band_list = [
  [ 1,"Future Islands", "Maryland", "google.com", "Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.", "http://c4.staticflickr.com/8/7674/17562456899_0d3dcd79f2_h.jpg", 1, "Band" ],
  [ 2,"Boy", "Rock", "google.com", "Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.", "http://c4.staticflickr.com/8/7674/17562456899_0d3dcd79f2_h.jpg", 2, "Band" ],
  [ 3,"The Kickback", "Illinois", "google.com", "Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.", "http://c4.staticflickr.com/8/7674/17562456899_0d3dcd79f2_h.jpg", 3, "Band" ],
  [ 4,"Jack Hotel", "Nebraska", "google.com", "Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.", "http://c4.staticflickr.com/8/7674/17562456899_0d3dcd79f2_h.jpg", 4, "Band" ],
  [ 5,"Twinsmith", "Nebraska", "google.com", "Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.", "http://c4.staticflickr.com/8/7674/17562456899_0d3dcd79f2_h.jpg", 5, "Band" ],
  [ 6,"AZP", "Nebraska", "google.com", "Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.", "http://c4.staticflickr.com/8/7674/17562456899_0d3dcd79f2_h.jpg", 6, "Band" ]
]

band_list.each do |id, name, origin, website, bio, image, headline_order|
  Band.create(id: id, name: name, origin: origin, website: website, bio: bio, remote_image_url: image, headline_order: headline_order)
end

comedian_list = [
  [ 7,"Hank Misterson", "Nebraska", "google.com", "Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.", "http://img.ccrd.clearchannel.com/media/mlib/2135/2014/07/default/jeremy_messersmith_0_1404235725.jpg", 1],
  [ 8, "Larissa Mursterson", "Germany", "google.com", "Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.", "http://img.ccrd.clearchannel.com/media/mlib/2135/2014/07/default/jeremy_messersmith_0_1404235725.jpg", 2],
  [ 9, "Helen Masterson", "Illinois", "google.com", "Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.", "http://img.ccrd.clearchannel.com/media/mlib/2135/2014/07/default/jeremy_messersmith_0_1404235725.jpg", 3]
]
comedian_list.each do |id, name, origin, website, bio, image, headline_order|
  Comedian.create(id:id, name: name, origin: origin, website: website, bio: bio, remote_image_url: image, headline_order: headline_order)
end

venue_list = [
  [ 1, "The Bourbon", "1415 O St, Lincoln, NE", "Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.", "http://inflatableferret.com/wp-content/uploads/2010/04/bourbon1.jpg", 40.813354, -96.700616, "http://bourbontheatre.com/", "http://i.imgur.com/Fxf20Oy.png"],
  [ 2, "Duffy's Tavern", "1412 E O St, Lincoln, NE", "Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.", "http://inflatableferret.com/wp-content/uploads/2010/04/bourbon1.jpg", 40.813794, -96.7007465, "http://duffyslincoln.com/", "http://i.imgur.com/jTQ0goI.png"],
  [ 3, "Yia Yia's Pizza", "1423 O St, Lincoln, NE", "Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.", "http://inflatableferret.com/wp-content/uploads/2010/04/bourbon1.jpg", 40.813265, -96.7004825, "https://www.facebook.com/yiayias/", "http://i.imgur.com/Pj3KcRP.png"],
  [ 4, "Bodega's Alley", "1418 O St, Lincoln, NE", "Good Times. Good People. Lincoln's home for JAM music since 1996.", "http://www.exploredowntown.org/_files/images/bod_2.jpg", 40.813882, -96.70058389999997, "http://www.bodegasalley.com/", "http://i.imgur.com/b8d73ou.png"],
  [ 5, "Single Barrel", "130 N 10th St, Lincoln, NE", "Down-home steak joint offering locally sourced meats & craft beers, plus a whiskey bar & live music.", "http://www.thesinglebarrel.com/wp-content/plugins/nivo-slider/timthumb.php?src=http://www.thesinglebarrel.com/wp-content/uploads/2012/08/img_26701.jpg&h=245&w=662&zc=1&q=100", 40.814451, -96.706641, "http://www.thesinglebarrel.com/", "http://i.imgur.com/RuS3Wy4.png"],
  [ 6, "Zoo Bar", "136 N 14th St, Lincoln, NE", "Happening tavern delivering live blues & jazz music almost every night of the week since 1973.", "https://i.imgur.com/UxOkTpI.jpg", 40.712784, -74.005941, "http://www.zoobar.com/ZOOFEST-News.html", "http://i.imgur.com/ZycuHbI.png"]
]
venue_list.each do |id, name, address, info, img, latitude, longitude, website, map_icon|
  Venue.create(id: id, name: name, address: address, info: info, remote_img_url: img, latitude: latitude, longitude: longitude, website: website, remote_map_icon_url: map_icon)
end

feature_list = [
  ["Mayor Beutler will drink three fishbowls if Lincoln Calling sells out", 1, "content content content content content content content content content content content content content content content content content content content content content content content content content", "http://farm4.staticflickr.com/3669/10346154844_3220d0685d_z.jpg","2016-05-26 21:55:19"],
  ["Test Article 2", 1, "content content content content content content content content content content content content content content content content content content content content content content content content content", "http://farm4.staticflickr.com/3669/10346154844_3220d0685d_z.jpg","2016-08-26 21:55:19"],
  ["Test Article 3 A Very Fascinating Article", 1, "content content content content content content content content content content content content content content content content content content content content content content content content content", "http://farm4.staticflickr.com/3669/10346154844_3220d0685d_z.jpg","2016-05-15 21:55:19"]
]
feature_list.each do |title, user_id, article_content, image, publish_date_time|
  Feature.create(title: title, user_id: user_id, article_content: article_content, remote_image_url: image, publish_date_time: publish_date_time)
end

faq_list = [
  ["Test FAQ 1 Question Question", 1, "content content content content content content content content content content content content content content content content content content content content content content content content content","2016-05-26 21:55:19"],
  ["Test FAQ 2 Question Question Question Question", 1, "content content content content content content content content content content content content content content content content content content content content content content content content content","2016-08-26 21:55:19"],
  ["Test FAQ 3 Question Question", 1, "content content content content content content content content content content content content content content content content content content content content content content content content content","2016-05-15 21:55:19"]
]
faq_list.each do |title, user_id, article_content, publish_date_time|
  Faq.create(title: title, user_id: user_id, article_content: article_content, publish_date_time: publish_date_time)
end

visitor_guide_list = [
  ["Test Article 1: A Long Titled Article", 1, "content content content content content content content content content content content content content content content content content content content content content content content content content", "http://farm4.staticflickr.com/3687/12160205823_fafd2cb706_z.jpg","2016-05-26 21:55:19"],
  ["Test Article 2", 1, "content content content content content content content content content content content content content content content content content content content content content content content content content", "http://farm4.staticflickr.com/3687/12160205823_fafd2cb706_z.jpg","2016-08-26 21:55:19"],
  ["Test Article 3 A Very Fascinating Article", 1, "content content content content content content content content content content content content content content content content content content content content content content content content content", "http://farm4.staticflickr.com/3687/12160205823_fafd2cb706_z.jpg","2016-05-15 21:55:19"]
]
visitor_guide_list.each do |title, user_id, article_content, image, publish_date_time|
  VisitorGuide.create(title: title, user_id: user_id, article_content: article_content, remote_image_url: image, publish_date_time: publish_date_time)
end

About.create(title: "About", user_id: 1, article_content: "content content content content content content content content content content content content content content content content content content content content content content content content content",publish_date_time: "2016-05-26 21:55:19")

events_list = [
  [1,1,21,"2016-10-06 19:00:00","2016-10-06 19:30:00"],
  [2,2,18,"2016-10-06 21:00:00","2016-10-06 21:30:00"],
  [3,3,0,"2016-10-06 22:00:00","2016-10-06 23:30:00"],
  [4,1,21,"2016-10-07 19:00:00","2016-10-07 19:30:00"],
  [5,2,18,"2016-10-07 21:00:00","2016-10-07 21:30:00"],
  [6,1,21,"2016-10-07 22:00:00","2016-10-07 22:30:00"],
  [7,3,0,"2016-10-08 19:00:00","2016-10-08 19:30:00"],
  [8,2,18,"2016-10-08 21:00:00","2016-10-08 22:30:00"],
  [9,1,21,"2016-10-08 22:00:00","2016-10-08 22:30:00"]
]
events_list.each do |artist_id, venue_id, minimum_age, start_date_time, end_date_time|
  Event.create(artist_id: artist_id, venue_id: venue_id, minimum_age: minimum_age, start_date_time: start_date_time, end_date_time: end_date_time)  
end

sponsors_list = [
  ["Hudl", "google.com",true,"content content content content",1,"http://static1.squarespace.com/static/5080b308e4b0b2058063657f/t/54c6cd37e4b00fa947e1a926/1422314808226/hudl-metro-orange-large.png"],
  ["Omaha Code School", "google.com",true,"content content content content",2,"http://omahacodeschool.com/assets/ocs_star_top-81abf4e4d763d3373b406fe469150d8d.png"],
  ["Firespring", "google.com",true,"content content content content",3,"https://pbs.twimg.com/profile_images/378800000580583830/91d8cd8383218224472850aa6e836ff1_400x400.png"],
  ["Other Sponsor1", "google.com",false,"content content content content",4,"http://logok.org/wp-content/uploads/2014/04/Apple-Logo-black.png"],
  ["Other Sponsor2", "google.com",false,"content content content content",4,"http://logok.org/wp-content/uploads/2014/04/Apple-Logo-black.png"],
  ["Other Sponsor3", "google.com",false,"content content content content",4,"http://logok.org/wp-content/uploads/2014/04/Apple-Logo-black.png"]
]
sponsors_list.each do |name, website, premier, description, sponsor_order, logo|
  Sponsor.create(name: name, website: website, premier: premier, description:description, sponsor_order:sponsor_order, remote_logo_url:logo)
end

tickets_list = [
  ["Three Day Pass", "http://wwww.eventbrite.com", 3000, true],
  ["Thursday", "http://wwww.eventbrite.com", 1500, false],
  ["Friday", "http://wwww.eventbrite.com", 1500, false],
  ["Saturday", "http://wwww.eventbrite.com", 1500, false]
]
tickets_list.each do |name, link, price_in_cents, sold_out|
  Ticket.create(name: name, link: link, price_in_cents: price_in_cents, sold_out: sold_out)
end


genres_list = [
  [ 1, "Rock", "http://farm4.staticflickr.com/3669/10346154844_3220d0685d_z.jpg"],
  [ 2, "Jazz", "http://farm4.staticflickr.com/3669/10346154844_3220d0685d_z.jpg"],
  [ 3, "Hip-Hop", "http://farm4.staticflickr.com/3669/10346154844_3220d0685d_z.jpg"],
  [ 4, "Country", "http://farm4.staticflickr.com/3669/10346154844_3220d0685d_z.jpg"],
  [ 5, "Folk", "http://farm4.staticflickr.com/3669/10346154844_3220d0685d_z.jpg"]
]
genres_list.each do |id, name, image|
  Genre.create(id: id, name: name, remote_image_url: image)
end

artists_genres_list = [
 [1, 1],
 [1, 2],
 [2, 1],
 [5, 1],
 [5, 3],
 [4, 5],
 [4, 1],
 [4, 4],
 [6, 1],
 [3, 1],
 [3, 4]
]
artists_genres_list.each do |artist_id, genre_id|
  Genre::HABTM_Artists.create(artist_id: artist_id, genre_id: genre_id)
end



# Article.create!([
#   {title: "Test Article 1: A Long Titled Article", user_id: 1, article_content: "content content content content content content content content content content content content content content content content content content content content content content content content content", image: "10346154844_3220d0685d_z.jpg", publish_date_time: "2016-05-26 21:55:19", type: "Feature"},
#   {title: "Test Article 2", user_id: 1, article_content: "content content content content content content content content content content content content content content content content content content content content content content content content content", image: "10346154844_3220d0685d_z.jpg", publish_date_time: "2016-08-26 21:55:19", type: "Feature"},
#   {title: "Test Article 3 A Very Fascinating Article", user_id: 1, article_content: "content content content content content content content content content content content content content content content content content content content content content content content content content", image: "10346154844_3220d0685d_z.jpg", publish_date_time: "2016-05-15 21:55:19", type: "Feature"},
#   {title: "Test FAQ 1 Question Question", user_id: 1, article_content: "content content content content content content content content content content content content content content content content content content content content content content content content content", image: nil, publish_date_time: "2016-05-26 21:55:19", type: "Faq"},
#   {title: "Test FAQ 2 Question Question Question Question", user_id: 1, article_content: "content content content content content content content content content content content content content content content content content content content content content content content content content", image: nil, publish_date_time: "2016-08-26 21:55:19", type: "Faq"},
#   {title: "Test FAQ 3 Question Question", user_id: 1, article_content: "content content content content content content content content content content content content content content content content content content content content content content content content content", image: nil, publish_date_time: "2016-05-15 21:55:19", type: "Faq"},
#   {title: "Test Article 1: A Long Titled Article", user_id: 1, article_content: "content content content content content content content content content content content content content content content content content content content content content content content content content", image: "12160205823_fafd2cb706_z.jpg", publish_date_time: "2016-05-26 21:55:19", type: "Visitor"},
#   {title: "Test Article 2", user_id: 1, article_content: "content content content content content content content content content content content content content content content content content content content content content content content content content", image: "12160205823_fafd2cb706_z.jpg", publish_date_time: "2016-08-26 21:55:19", type: "Visitor"},
#   {title: "Test Article 3 A Very Fascinating Article", user_id: 1, article_content: "content content content content content content content content content content content content content content content content content content content content content content content content content", image: "12160205823_fafd2cb706_z.jpg", publish_date_time: "2016-05-15 21:55:19", type: "Visitor"},
#   {title: "About", user_id: 1, article_content: "content content content content content content content content content content content content content content content content content content content content content content content content content", image: nil, publish_date_time: "2016-05-26 21:55:19", type: "About"}
# ])
# Artist.create!([
#   {name: "Future Islands", genre: "Rock", origin: "Maryland", website: "google.com", bio: "Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.", image: "17562456899_0d3dcd79f2_h.jpg", headline_order: 1, type: "Band"},
#   {name: "Boy", genre: "Rock", origin: "Germany", website: "google.com", bio: "Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.", image: "17562456899_0d3dcd79f2_h.jpg", headline_order: 2, type: "Band"},
#   {name: "The Kickback", genre: "Pop", origin: "Illinois", website: "google.com", bio: "Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.", image: "17562456899_0d3dcd79f2_h.jpg", headline_order: 3, type: "Band"},
#   {name: "Jack Hotel", genre: "Pop", origin: "Nebraska", website: "google.com", bio: "Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.", image: "17562456899_0d3dcd79f2_h.jpg", headline_order: 4, type: "Band"},
#   {name: "Twinsmith", genre: "Rock", origin: "Nebraska", website: "google.com", bio: "Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.", image: "17562456899_0d3dcd79f2_h.jpg", headline_order: 5, type: "Band"},
#   {name: "AZP", genre: "Folk", origin: "Nebraska", website: "google.com", bio: "Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.", image: "17562456899_0d3dcd79f2_h.jpg", headline_order: 6, type: "Band"},
#   {name: "Hank Misterson", genre: nil, origin: "Nebraska", website: "google.com", bio: "Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.", image: "jeremy_messersmith_0_1404235725.jpg", headline_order: 1, type: "Comedian"},
#   {name: "Larissa Mursterson", genre: nil, origin: "Germany", website: "google.com", bio: "Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.", image: "jeremy_messersmith_0_1404235725.jpg", headline_order: 2, type: "Comedian"},
#   {name: "Helen Masterson", genre: nil, origin: "Illinois", website: "google.com", bio: "Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.", image: "jeremy_messersmith_0_1404235725.jpg", headline_order: 3, type: "Comedian"},
#   {name: "3 Son Green", genre: "Funk", origin: "Missouri", website: "http://3songreen.com/", bio: "Since 2007, 3 Son Green has been interweaving their vast web of sound, sense and solidarity into the ever‐evolving architect it has become. Their RockJamJazzFunk style breaks genre bylaws, and pulls crowds out of their seats everywhere they play. 3 Son Green’s intricate songwriting combined with their natural improvisation is guaranteed to satisfy every music lover’s palette. Their well-fueled, expanding flame has, even now, lapped at the feet of the music world at all manner of festivals across the Midwest. These Kansas City grown virtuosos are vaulting to new heights, and leaving no slack behind.", image: "bobdylan3.jpg", headline_order: 8, type: "Band"},
#   {name: "The Midland Band", genre: "Rock", origin: "Nebraska", website: "https://www.facebook.com/themidlandband/info/?tab=overview", bio: "Originating from Columbus, Nebraska, the Midland Band has been bringing an aggressive brand of improvisational 70's jazz/rock to the masses. Known for their dual guitars, keyboard heavy, intense, and yet dance-able music, the Midland Band brings a great amount of energy to any stage they take on.", image: "bobdylan3.jpg", headline_order: 9, type: "Band"}
# ])
# Event.create!([
#   {artist_id: 1, venue_id: 1, minimum_age: "21", start_date_time: "2016-10-06 19:00:00", end_date_time: "2016-10-06 19:30:00"},
#   {artist_id: 2, venue_id: 2, minimum_age: "18", start_date_time: "2016-10-06 21:00:00", end_date_time: "2016-10-06 21:30:00"},
#   {artist_id: 3, venue_id: 3, minimum_age: "0", start_date_time: "2016-10-06 22:00:00", end_date_time: "2016-10-06 23:30:00"},
#   {artist_id: 4, venue_id: 1, minimum_age: "21", start_date_time: "2016-10-07 19:00:00", end_date_time: "2016-10-07 19:30:00"},
#   {artist_id: 5, venue_id: 2, minimum_age: "18", start_date_time: "2016-10-07 21:00:00", end_date_time: "2016-10-07 21:30:00"},
#   {artist_id: 6, venue_id: 1, minimum_age: "21", start_date_time: "2016-10-07 22:00:00", end_date_time: "2016-10-07 22:30:00"},
#   {artist_id: 7, venue_id: 3, minimum_age: "0", start_date_time: "2016-10-08 19:00:00", end_date_time: "2016-10-08 19:30:00"},
#   {artist_id: 8, venue_id: 2, minimum_age: "18", start_date_time: "2016-10-08 21:00:00", end_date_time: "2016-10-08 22:30:00"},
#   {artist_id: 9, venue_id: 1, minimum_age: "21", start_date_time: "2016-10-08 22:00:00", end_date_time: "2016-10-08 22:30:00"},
#   {artist_id: 10, venue_id: 4, minimum_age: "21", start_date_time: "2016-10-06 21:30:00", end_date_time: "2016-10-06 22:30:00"},
#   {artist_id: 11, venue_id: 4, minimum_age: "21", start_date_time: "2016-10-06 23:45:00", end_date_time: "2016-10-07 01:30:00"}
# ])
# Sponsor.create!([
#   {name: "Hudl", website: "google.com", premier: true, description: "content content content content", sponsor_order: 1, logo: "hudl-metro-orange-large.png"},
#   {name: "Omaha Code School", website: "google.com", premier: true, description: "content content content content", sponsor_order: 2, logo: "ocs_star_top-81abf4e4d763d3373b406fe469150d8d.png"},
#   {name: "Firespring", website: "google.com", premier: true, description: "content content content content", sponsor_order: 3, logo: "91d8cd8383218224472850aa6e836ff1_400x400.png"},
#   {name: "Other Sponsor1", website: "google.com", premier: false, description: "content content content content", sponsor_order: 4, logo: "Apple-Logo-black.png"},
#   {name: "Other Sponsor2", website: "google.com", premier: false, description: "content content content content", sponsor_order: 4, logo: "Apple-Logo-black.png"},
#   {name: "Other Sponsor3", website: "google.com", premier: false, description: "content content content content", sponsor_order: 4, logo: "Apple-Logo-black.png"}
# ])
# Ticket.create!([
#   {name: "Three Day Pass", link: "http://wwww.eventbrite.com", price_in_cents: 3000, eventbrite_id: nil, sold_out: true},
#   {name: "Thursday", link: "http://wwww.eventbrite.com", price_in_cents: 1500, eventbrite_id: nil, sold_out: false},
#   {name: "Friday", link: "http://wwww.eventbrite.com", price_in_cents: 1500, eventbrite_id: nil, sold_out: false},
#   {name: "Saturday", link: "http://wwww.eventbrite.com", price_in_cents: 1500, eventbrite_id: nil, sold_out: false}
# ])
# Venue.create!([
#   {name: "The Bourbon", address: "1415 O St, Lincoln, NE", info: "Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.", img: "bourbon1.jpg", latitude: 40.8132777, longitude: -96.7006209, website: "http://bourbontheatre.com/", map_icon: "Fxf20Oy.png"},
#   {name: "Duffy's Tavern", address: "1412 E O St, Lincoln, NE", info: "Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.", img: "bourbon1.jpg", latitude: 40.8137839, longitude: -96.7008024, website: "http://duffyslincoln.com/", map_icon: "jTQ0goI.png"},
#   {name: "Yia Yia's Pizza", address: "1423 O St, Lincoln, NE", info: "Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.", img: "bourbon1.jpg", latitude: 40.8132565, longitude: -96.7004739, website: "https://www.facebook.com/yiayias/", map_icon: "Pj3KcRP.png"},
#   {name: "Bodega's Alley", address: "1418 O St, Lincoln, NE", info: "Good Times. Good People. Lincoln's home for JAM music since 1996.", img: "bod_2.jpg", latitude: 40.8138818, longitude: -96.7005839, website: "http://www.bodegasalley.com/", map_icon: "b8d73ou.png"},
#   {name: "Single Barrel", address: "130 N 10th St, Lincoln, NE", info: "Down-home steak joint offering locally sourced meats & craft beers, plus a whiskey bar & live music.", img: "timthumb.php", latitude: 40.8144514, longitude: -96.7066409, website: "http://www.thesinglebarrel.com/", map_icon: "RuS3Wy4.png"},
#   {name: "Zoo Bar", address: "136 N 14th St, Lincoln, NE", info: "Happening tavern delivering live blues & jazz music almost every night of the week since 1973.", img: "UxOkTpI.jpg", latitude: 40.8143776, longitude: -96.7008083, website: "http://www.zoobar.com/ZOOFEST-News.html", map_icon: "ZycuHbI.png"},
#   {name: "Tavern on the Square", address: "816 P St, Lincoln, NE", info: "Tavern on the Square is a locals hang out in the Historic Haymarket. Tavern offers outdoor seating in a large courtyard. Activities include darts, bags, cards and buck hunter.", img: "fQbMdJ2.jpg", latitude: 40.8149741, longitude: -96.7093937, website: "https://www.facebook.com/Tavern-on-the-Square-238709169482275/", map_icon: "peach.png"},
#   {name: "White Rabbit", address: "1140 O ST Lincoln, Ne", info: "Follow the White Rabbit...", img: "Bourbon_Theater.png", latitude: 40.8139286, longitude: -96.7043634, website: "http://www.whiterabbitlincoln.com/", map_icon: "green.png"},
#   {name: "Tower Square", address: "13th & P Street. Lincoln, NE", info: "Lincoln Community Foundation Tower Square is an 18,000 square foot park highlighted by a 57-foot-tall, internally illuminated, multicolor column, known as Ascent Tower, by artist Jun Kaneko.\r\n\r\n- See more at: http://downtownlincoln.org/explore/p-street/tower-square.html#sthash.Z7qA42YL.dpuf", img: "Bourbon_Theater.png", latitude: 40.814749, longitude: -96.702584, website: "http://downtownlincoln.org/explore/p-street/tower-square.html", map_icon: "blue.png"}
# ])
# About.create!([
#   {title: "About", user_id: 1, article_content: "content content content content content content content content content content content content content content content content content content content content content content content content content", image: nil, publish_date_time: "2016-05-26 21:55:19", type: "About"}
# ])
# Faq.create!([
#   {title: "Test FAQ 1 Question Question", user_id: 1, article_content: "content content content content content content content content content content content content content content content content content content content content content content content content content", image: nil, publish_date_time: "2016-05-26 21:55:19", type: "Faq"},
#   {title: "Test FAQ 2 Question Question Question Question", user_id: 1, article_content: "content content content content content content content content content content content content content content content content content content content content content content content content content", image: nil, publish_date_time: "2016-08-26 21:55:19", type: "Faq"},
#   {title: "Test FAQ 3 Question Question", user_id: 1, article_content: "content content content content content content content content content content content content content content content content content content content content content content content content content", image: nil, publish_date_time: "2016-05-15 21:55:19", type: "Faq"}
# ])
# Feature.create!([
#   {title: "Test Article 1: A Long Titled Article", user_id: 1, article_content: "content content content content content content content content content content content content content content content content content content content content content content content content content", image: "10346154844_3220d0685d_z.jpg", publish_date_time: "2016-05-26 21:55:19", type: "Feature"},
#   {title: "Test Article 2", user_id: 1, article_content: "content content content content content content content content content content content content content content content content content content content content content content content content content", image: "10346154844_3220d0685d_z.jpg", publish_date_time: "2016-08-26 21:55:19", type: "Feature"},
#   {title: "Test Article 3 A Very Fascinating Article", user_id: 1, article_content: "content content content content content content content content content content content content content content content content content content content content content content content content content", image: "10346154844_3220d0685d_z.jpg", publish_date_time: "2016-05-15 21:55:19", type: "Feature"}
# ])
# Visitor.create!([
#   {title: "Test Article 1: A Long Titled Article", user_id: 1, article_content: "content content content content content content content content content content content content content content content content content content content content content content content content content", image: "12160205823_fafd2cb706_z.jpg", publish_date_time: "2016-05-26 21:55:19", type: "Visitor"},
#   {title: "Test Article 2", user_id: 1, article_content: "content content content content content content content content content content content content content content content content content content content content content content content content content", image: "12160205823_fafd2cb706_z.jpg", publish_date_time: "2016-08-26 21:55:19", type: "Visitor"},
#   {title: "Test Article 3 A Very Fascinating Article", user_id: 1, article_content: "content content content content content content content content content content content content content content content content content content content content content content content content content", image: "12160205823_fafd2cb706_z.jpg", publish_date_time: "2016-05-15 21:55:19", type: "Visitor"}
# ])
# Band.create!([
#   {name: "Future Islands", genre: "Rock", origin: "Maryland", website: "google.com", bio: "Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.", image: "17562456899_0d3dcd79f2_h.jpg", headline_order: 1, type: "Band"},
#   {name: "Boy", genre: "Rock", origin: "Germany", website: "google.com", bio: "Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.", image: "17562456899_0d3dcd79f2_h.jpg", headline_order: 2, type: "Band"},
#   {name: "The Kickback", genre: "Pop", origin: "Illinois", website: "google.com", bio: "Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.", image: "17562456899_0d3dcd79f2_h.jpg", headline_order: 3, type: "Band"},
#   {name: "Jack Hotel", genre: "Pop", origin: "Nebraska", website: "google.com", bio: "Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.", image: "17562456899_0d3dcd79f2_h.jpg", headline_order: 4, type: "Band"},
#   {name: "Twinsmith", genre: "Rock", origin: "Nebraska", website: "google.com", bio: "Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.", image: "17562456899_0d3dcd79f2_h.jpg", headline_order: 5, type: "Band"},
#   {name: "AZP", genre: "Folk", origin: "Nebraska", website: "google.com", bio: "Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.", image: "17562456899_0d3dcd79f2_h.jpg", headline_order: 6, type: "Band"},
#   {name: "3 Son Green", genre: "Funk", origin: "Missouri", website: "http://3songreen.com/", bio: "Since 2007, 3 Son Green has been interweaving their vast web of sound, sense and solidarity into the ever‐evolving architect it has become. Their RockJamJazzFunk style breaks genre bylaws, and pulls crowds out of their seats everywhere they play. 3 Son Green’s intricate songwriting combined with their natural improvisation is guaranteed to satisfy every music lover’s palette. Their well-fueled, expanding flame has, even now, lapped at the feet of the music world at all manner of festivals across the Midwest. These Kansas City grown virtuosos are vaulting to new heights, and leaving no slack behind.", image: "bobdylan3.jpg", headline_order: 8, type: "Band"},
#   {name: "The Midland Band", genre: "Rock", origin: "Nebraska", website: "https://www.facebook.com/themidlandband/info/?tab=overview", bio: "Originating from Columbus, Nebraska, the Midland Band has been bringing an aggressive brand of improvisational 70's jazz/rock to the masses. Known for their dual guitars, keyboard heavy, intense, and yet dance-able music, the Midland Band brings a great amount of energy to any stage they take on.", image: "bobdylan3.jpg", headline_order: 9, type: "Band"}
# ])
# Comedian.create!([
#   {name: "Hank Misterson", genre: nil, origin: "Nebraska", website: "google.com", bio: "Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.", image: "jeremy_messersmith_0_1404235725.jpg", headline_order: 1, type: "Comedian"},
#   {name: "Larissa Mursterson", genre: nil, origin: "Germany", website: "google.com", bio: "Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.", image: "jeremy_messersmith_0_1404235725.jpg", headline_order: 2, type: "Comedian"},
#   {name: "Helen Masterson", genre: nil, origin: "Illinois", website: "google.com", bio: "Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.Lorem ipsum dolor sit amet, putent propriae adversarium mel an, congue legere suscipit his at. Nec oblique prompta ex. Utinam eirmod convenire mea te, sed sint urbanitas interesset ea. Cum dolor aliquip aliquando ad, in dicta cetero insolens pri. Ex pro vidit option definitionem.", image: "jeremy_messersmith_0_1404235725.jpg", headline_order: 3, type: "Comedian"}
# ])

